image:
  repository: ghcr.io/lilianasacorreia/fhir-processor
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082   # ajusta se o teu servi√ßo usar outra porta

resources: {}

env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda:9092

# Exemplo:
# env:
#   - name: KAFKA_BOOTSTRAP
#     value: redpanda:9092
#   - name: FHIR_SERVER_URL
#     value: http://hapi-fhir:8080/fhir

config:
  enabled: false
  data: {}
  # Exemplo:
  # data:
  #   processor.properties: |
  #     processor.batch.size=100
  #     processor.mode=async

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
