image:
  repository: ghcr.io/lilianasacorreia/fhir-processor
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082   # ajusta se o teu servi√ßo usar outra porta

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1Gi

env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda:9093
  - name: FHIR_SERVER_URL
    value: http://hapi-fhir:8080/fhir

config:
  enabled: true
  data: {}
  # Exemplo:
  # data:
  #   processor.properties: |
  #     processor.batch.size=100
  #     processor.mode=async

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
